services:
  captcha-solver:
    image: vevc/captcha-solver
    container_name: captcha-solver
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN:-}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "2"
