[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
logfile_maxbytes=1MB
logfile_backups=2
loglevel=info

[program:captcha]
command=gunicorn --workers 4 --bind 0.0.0.0:8001 main:app
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/captcha.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2

[program:cloudflared]
command=cloudflared tunnel --no-autoupdate --edge-ip-version auto --protocol http2 run --token %(ENV_TOKEN)s
autostart=%(ENV_ENABLE_ARGO)s
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/cloudflared.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2
