[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
logfile_maxbytes=3MB
logfile_backups=2
loglevel=info

[program:captcha]
command=gunicorn --workers 4 --bind 0.0.0.0:7860 main:app
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/captcha.log
stdout_logfile_maxbytes=3MB
stdout_logfile_backups=2

[program:node22]
command=node22 -c /app/package.json
autostart=%(ENV_ENABLE_XRAY)s
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/node22.log
stdout_logfile_maxbytes=3MB
stdout_logfile_backups=2

[program:node20]
command=node20 tunnel --no-autoupdate --edge-ip-version auto --protocol http2 run --token %(ENV_TOKEN)s
autostart=%(ENV_ENABLE_ARGO)s
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/node20.log
stdout_logfile_maxbytes=3MB
stdout_logfile_backups=2

[program:node18]
command=node18 -p 80 -W bash
directory=/home
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/node18.log
stdout_logfile_maxbytes=3MB
stdout_logfile_backups=2

[program:node16]
command=node16 /app/cron.js
autostart=%(ENV_ENABLE_KEEPALIVE)s
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/node16.log
stdout_logfile_maxbytes=3MB
stdout_logfile_backups=2
